#!/bin/bash -ex

git clone https://github.com/scheib/chromium-latest-linux

echo "contents of chromedriver-work:" 

./chromium-latest-linux/update-and-run.sh && echo "finished"

sudo find ./chromium-latest-linux -name 'chrome' -exec mv -v {} /usr/local/bin/chromium \; && echo "moved" 

if chromium --version; then 
    echo "success" 
else 
    echo "error" 
fi
